version: '3'
services:
  server:
    build: ./server
    container_name: node-server
    depends_on:
      - redis
    ports:
      - '8080:8080'
    links:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    restart: always